### PR TITLE
Issues Fixed: Backend, Frontend UI and much more

### LINKED ISSUE #10: Issue: Backend not working properly
Whenever we try to add some transaction , there is error that is poping up in the console 

image
image

### PR DESCRIPTION
**Pull request by jiveshkalra**
**Fixed [Issue #10 ](https://github.com/BTANISHA11/ExpenseTracker/issues/10)**

## Changes -> 
- [x]  Fixed Backend 
- [x]  Added A Price option in frontend UI
- [x]  Made all the fields of form mandatory
- [x]  Improved UI of the frontend
- [x]  Fixed running of both front end and backend simultaneously
- [x]  Fixed Loading of all the transaction 

## Screenshots ->
 
image
image

### CODE REVIEW

**Comment by jiveshkalra** [comment]
Took a while , but I think it was worth it :)

**Comment by jiveshkalra** [comment]
Also ignore this stupid gitguardian , I removed the secrets from public and it misunderstands it as if i added it to it.

**Comment by BTANISHA11** [comment]
> Also ignore this stupid gitguardian , I removed the secrets from public and it misunderstands it as if i added it to it.

still when submitting form it is giving error in console .
pls fix that.

**Comment by jiveshkalra** [comment]
that error might be because of the missing .env in the vercel or at your local host 
please create a file named .env in the `/api/ ` folder and then add your mongo db url in that , as shown in here ->
`MONGO_URL="{Your MongoDb URL HERE}"`
and keep it private in your local host or in your vercel 
(detailed instructions are given in a README .txt file as well in the /api/ folder)

**Comment by BTANISHA11** [comment]
ok great

**Pull request merged**
